### ISSUE TITLE
I converted it to a rails app for you

### ISSUE THREAD

**Issue by andrewcottage** [LordAlexWorks/proactives#1]
https://github.com/andrewcottage/proactives-rails

I applied to your odesk ad. Finished the job.

You don't have to pay me or anything, but could you hire me and give me 5 stars?

Kind Regards

**Comment by bolom** [comment]
I have already sent you an offer. Tks dude.

The job is not finish 

* we have to add the french version
* in bottom there is contact form. we need to add the backend logic

Do you want to work on it ?
