### ISSUE TITLE
Please change all $ for €

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/proactives#12]

**Comment by hassanakram** [comment]
Fixed

**Comment by bolom** [comment]
@kkannappan ready to QA

**Comment by kkannappan** [comment]
@bolom

Tested in all major browsers, issue is fixed. All currencies are now in 'Euro'.

![pro - currency change](https://cloud.githubusercontent.com/assets/2522583/5873264/86e143ba-a31a-11e4-92e8-062bcb04c165.png)
