### ISSUE TITLE
Homepage - 'Approved' is mis-spelt as 'Approuved'

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/proactives#17]
Please correct the typo.

![pro - approved misspelt](https://cloud.githubusercontent.com/assets/2522583/5873712/68a9d218-a31f-11e4-8ffe-5b7468d07d05.png)

**Comment by hassanakram** [comment]
@kkannappan  ready to QA

**Comment by kkannappan** [comment]
@hassanakram 

Verified in all major browsers, issue is fixed. Closing the issue.
