### ISSUE TITLE
Sign Up section - Change the Font colour of the placeholder text

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/proactives#18]
The font color as seen in Chrome 38.0 and FireFox 35.0 browsers are not clearly visible to the user, please change it to a darker coloured font. The font is clearly visible in IE 11 browser.

![pro - font colour of the form](https://cloud.githubusercontent.com/assets/2522583/5873957/594b7dc8-a322-11e4-8baa-90f375b554a4.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
@hassanakram 

Verified in all major browsers, issue is fixed. Closing the issue.
