### ISSUE TITLE
Our Packages section - Capitalization is not implemented correctly.

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/proactives#19]
The first package is given as 'Pro-Active', while the second package is shown as 'Pro-active plus'. Please change the second package name to 'Pro-Active Plus'.

![pro - package type capitalization](https://cloud.githubusercontent.com/assets/2522583/5874187/7d32a6ec-a324-11e4-8d20-cb18eb5034eb.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
@hassanakram 

Issue is partially fixed. The French site has been updated to reflect 'Pro-Active Plus', however, the English site still says 'Pro-Active plus'.

**Comment by hassanakram** [comment]
@kkannappan Fixed.

**Comment by kkannappan** [comment]
@hassanakram 

Verified in all major browsers, issue is fixed. Closing the issue.
