### ISSUE TITLE
French - Sign Up section has the text 'Type de forfait' is shown multiple times in the dropdown

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/proactives#20]
In the Sign Up section the Type of Package dropdown, shows the text 'Type de forfait' three times instead of showing the Package types. This is seen in all browsers.

![pro - type of package 3 times](https://cloud.githubusercontent.com/assets/2522583/5874269/80721620-a325-11e4-9079-055463ac4529.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
@hassanakram 

Verified in all major browsers, issue is fixed. Closing the issue.
