### ISSUE TITLE
Copyright text for French language should be in French

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/proactives#21]
The copyright text at the bottom of the page is currently 'Copyright © 2015 Pro-Active' for both English and French locales. It should be changed to 'Droit d'auteur © 2015 Pro-Active' when the site is viewed in French language.

![pro - change copyright text to fr](https://cloud.githubusercontent.com/assets/2522583/5878543/b554cca2-a34d-11e4-9a32-102f0b98f411.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA

**Comment by kkannappan** [comment]
@hassanakram 

Verified in all major browsers, issue is fixed. Closing the issue.
