### ISSUE TITLE
[test] good pratice and test

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/proactives#716]
- [x] install in local https://github.com/bbatsov/rubocop#installation
- [x] install houndci
- [x] implement Clircle-ci https://circleci.com/docs/continuous-deployment-with-heroku/
- [x] setup capybara
- [x] setup rspec

we will start to implement capybara and rspec from #1135 

I would like to follow that

https://robots.thoughtbot.com/how-we-test-rails-applications

Should i buy this book ?
https://gumroad.com/l/testing-rails

**Comment by rmonteiro89** [comment]
I dont think a book is necessary. Only if you really want to read it. You can find a lot of informatiion and examples in the internet.

I like this article, i have read it sometime ago. Gonna read it again. :+1:

**Comment by rmonteiro89** [comment]
https://robots.thoughtbot.com/four-phase-test
