### ISSUE TITLE
Deactivate 3 buttons on the top

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/proactives#9]
https://www.evernote.com/shard/s96/sh/aa6f5857-87b5-4230-817e-8f579c5b6b6b/ee9344e6d0adef7c75be049452ca5680

**Comment by hassanakram** [comment]
Fixed

**Comment by bolom** [comment]
@kkannappan ready to QA

**Comment by kkannappan** [comment]
@bolom 

Verifed in IE 11, Chrome and Firefox browsers, issue is fixed.

![pro - buttons removed](https://cloud.githubusercontent.com/assets/2522583/5872515/5d353a4c-a312-11e4-8fb8-88446eab0986.png)

**Comment by bolom** [comment]
@kkannappan did you test in french too ?

**Comment by kkannappan** [comment]
@bolom 

Nope, I tested in English only, seems not fixed in French language, re-opening the issue.

![pro - buttons not removed in fr](https://cloud.githubusercontent.com/assets/2522583/5872686/42440fcc-a314-11e4-8ba9-5497ef36e0f8.png)

**Comment by bolom** [comment]
@hassanakram can you please fix that in french too

**Comment by hassanakram** [comment]
@kkannappan please test this feature.

**Comment by kkannappan** [comment]
@hassanakram

Verified in all major browsers, issue is fixed. The 3 dots are now deactivated in both language sites, closing the issue.
